import Darwin
import Foundation

nonisolated enum SnapshotStoreError: LocalizedError {
    case rootUnavailable(String)
    case invalidIdentifier(String)
    case writeFailed(String)
    case alreadyExists(String)
    case notFound(String)

    var errorDescription: String? {
        switch self {
        case .rootUnavailable(let detail): return "the snapshot folder is unavailable: \(detail)"
        case .invalidIdentifier(let id): return "snapshot identifier \(id) is not a safe file name"
        case .writeFailed(let detail): return "the snapshot could not be written: \(detail)"
        case .alreadyExists(let id): return "a snapshot with identifier \(id) already exists and was not overwritten"
        case .notFound(let id): return "no snapshot with identifier \(id) is stored"
        }
    }
}

nonisolated struct SnapshotLoadFailure: Identifiable, Error {
    var id: String { fileName }
    var fileName: String
    var reason: String
    var header: SnapshotHeader?
}

// one json file per snapshot under application support
// the finished bytes are written to a scratch file first and only then published under
// the real name, so a reader never sees half a snapshot
// a file that cannot be read is reported and skipped, it never hides the others
nonisolated final class SnapshotStore {
    let root: URL

    init(root: URL) {
        self.root = root
    }

    static func defaultRoot() throws -> URL {
        let base = try FileManager.default.url(for: .applicationSupportDirectory,
                                               in: .userDomainMask,
                                               appropriateFor: nil,
                                               create: true)
        return base.appendingPathComponent("Anchor/Snapshots", isDirectory: true)
    }

    static func makeDefault() -> (store: SnapshotStore?, error: String?) {
        do {
            return (SnapshotStore(root: try defaultRoot()), nil)
        } catch {
            return (nil, error.localizedDescription)
        }
    }

    // ids are generated by anchor, the guard is here so a name or a path can never
    // become a file name by some later mistake
    static func isSafeIdentifier(_ id: String) -> Bool {
        guard (8...64).contains(id.count) else { return false }
        return id.allSatisfy { $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "-") }
    }

    static func newIdentifier() -> String { UUID().uuidString }

    func fileURL(for id: String) -> URL {
        root.appendingPathComponent("\(id).json", isDirectory: false)
    }

    func create(_ snapshot: Snapshot) throws {
        guard Self.isSafeIdentifier(snapshot.id) else { throw SnapshotStoreError.invalidIdentifier(snapshot.id) }
        try write(snapshot, replacingExisting: false)
    }

    func update(_ snapshot: Snapshot) throws {
        guard Self.isSafeIdentifier(snapshot.id) else { throw SnapshotStoreError.invalidIdentifier(snapshot.id) }
        guard FileManager.default.fileExists(atPath: fileURL(for: snapshot.id).path) else {
            throw SnapshotStoreError.notFound(snapshot.id)
        }
        try write(snapshot, replacingExisting: true)
    }

    func loadAll() -> (snapshots: [Snapshot], failures: [SnapshotLoadFailure]) {
        let manager = FileManager.default
        guard let names = try? manager.contentsOfDirectory(atPath: root.path) else {
            return ([], [])
        }
        var snapshots: [Snapshot] = []
        var failures: [SnapshotLoadFailure] = []
        for name in names.sorted() where name.hasSuffix(".json") && !name.hasPrefix(".") {
            switch load(fileName: name) {
            case .success(let snapshot): snapshots.append(snapshot)
            case .failure(let failure): failures.append(failure)
            }
        }
        snapshots.sort { $0.createdAt > $1.createdAt }
        return (snapshots, failures)
    }

    // every file is decoded on its own so one bad file loses only itself
    func load(fileName: String) -> Result<Snapshot, SnapshotLoadFailure> {
        let url = root.appendingPathComponent(fileName, isDirectory: false)
        guard let data = FileManager.default.contents(atPath: url.path) else {
            return .failure(SnapshotLoadFailure(fileName: fileName, reason: "the file could not be read", header: nil))
        }
        let decoder = Self.decoder
        let header = try? decoder.decode(SnapshotHeader.self, from: data)
        if let header, header.schemaVersion != SnapshotSchema.current {
            let reason = "written with snapshot schema version \(header.schemaVersion), this build reads version \(SnapshotSchema.current)"
            return .failure(SnapshotLoadFailure(fileName: fileName, reason: reason, header: header))
        }
        do {
            return .success(try decoder.decode(Snapshot.self, from: data))
        } catch {
            let reason = header == nil
                ? "the file is not a readable anchor snapshot"
                : "the file header is readable but the body is not: \(error.localizedDescription)"
            return .failure(SnapshotLoadFailure(fileName: fileName, reason: reason, header: header))
        }
    }

    private func write(_ snapshot: Snapshot, replacingExisting: Bool) throws {
        let data: Data
        do {
            data = try Self.encoder.encode(snapshot)
        } catch {
            throw SnapshotStoreError.writeFailed(error.localizedDescription)
        }

        do {
            try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        } catch {
            throw SnapshotStoreError.rootUnavailable(error.localizedDescription)
        }

        let temporary = root.appendingPathComponent(".\(UUID().uuidString).partial", isDirectory: false)
        do {
            try data.write(to: temporary, options: [.withoutOverwriting])
        } catch {
            throw SnapshotStoreError.writeFailed(error.localizedDescription)
        }
        defer { try? FileManager.default.removeItem(at: temporary) }

        let destination = fileURL(for: snapshot.id)
        if replacingExisting {
            do {
                _ = try FileManager.default.replaceItemAt(destination, withItemAt: temporary)
            } catch {
                throw SnapshotStoreError.writeFailed(error.localizedDescription)
            }
            return
        }
        // hard linking the finished file into place is atomic and refuses to clobber
        // an existing snapshot, so history cannot be lost to a repeated identifier
        guard link(temporary.path, destination.path) == 0 else {
            let code = errno
            if code == EEXIST { throw SnapshotStoreError.alreadyExists(snapshot.id) }
            throw SnapshotStoreError.writeFailed(String(cString: strerror(code)))
        }
    }

    static var encoder: JSONEncoder {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        encoder.dateEncodingStrategy = .iso8601
        return encoder
    }

    static var decoder: JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return decoder
    }
}
